language: node_js
node_js:
  - "8.0"
  - "7.2"
  - "6.9"
before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
install:
  - yarn install
  - yarn run build
script:
  - yarn run test
after_success:
  - yarn run coverage
