jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    maxParallel: 2
    matrix:
      node-10(LTS):
        node_version: ^10.13.0
      node-11(Current):
        node_version: ^11.1.0
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(node_version)
    displayName: 'Install Node.js'

  - script: |
      yarn
    displayName: 'Install dependencies'

  - script: |
      set JEST_JUNIT_OUTPUT=test-fixtures-junit.xml&& yarn test:fixtures -w=2
    displayName: 'Test: Build Fixtures'

  - script: |
      set JEST_JUNIT_OUTPUT=test-unit-junit.xml&& yarn test:unit -w=2
    displayName: 'Test: Run unit tests'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: 'test-*.xml'
    displayName: 'Publish test results to Azure Pipelines'
