name: build

on:
  push:
    branches:
    tags:
  pull_request:


jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    name: Build on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1

    - name: debug if needed
      run: |
        export DEBUG=${DEBUG:-false}
        if [[ "$DEBUG" == "true" ]]; then
          env
        fi
      env:
        DEBUG: ${{secrets.DEBUG}}

    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: 'Install dependencies'
      run: npm install --frozen-lockfile --non-interactive

    - name: 'Build'
      run: yarn test:fixtures --coverage && yarn coverage

    - name: 'Unit tests'
      run: yarn test:unit --coverage && yarn coverage

    - name: 'Tests e2e'
      run: yarn test:e2e
